var express = require("express");
var app=express();
var http = require("http").Server(app);
var score = require("./score");
var user = require("./user");
var trophy = require("./trophy");
var game =require("./game");
app.use("/api/score", score);
app.use("/api/user", user);
app.use("/api/trophy", trophy);
app.use("/api/game", game);
http.listen(8080);
